### ISSUE TITLE
Pass mode parameter to st_convolve from spike_density_estimation

### ISSUE THREAD

**Issue by iraikov** [rproepp/spykeutils#7]
In some cases it might be useful to specify 'valid' mode when convolving spike trains in order to avoid boundary effects. It would be convenient to have a mode parameter in spike_density_estimation that passes it to st_convolve. Thanks for the consideration!

**Comment by rproepp** [comment]
Sounds like a reasonable and small change. I'm not actively developing this package anymore, but if you can create a pull request I will have a look and can merge it!

**Comment by iraikov** [comment]
Hi Robert, thanks a lot for your response. I am still evaluating approaches for computing the instantaneous firing rate and have not settled on one yet. I will close this issue for now and revisit/submit a pull request if I still think it is worthwhile.
